language: node_js
node_js:
  - "7"
  - "6"
  - "4"
before_install:
  - npm install -g bulk-decaffeinate decaffeinate eslint
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
